import { getExampleInterface } from "./exampleApi";
import { createOntologyFunctionInterface, getOntologyFunctionListInterface } from "./functionApi";
import { postLoginInterface } from "./loginApi";
import { getOntologyDatasourceColumnsInterface, getOntologyDatasourceTablesInterface } from "./ontologyDatasourceApi";
import { getOntologyApiDocsInterface } from "./ontologyDocApi";
import { postOntologyGlobalSearchInterface } from "./ontologySearchApi";
import {
  createOntologySpaceInterface,
  createOntologySpaceWithCanvasContentInterface,
  deleteOntologyCategoryTreeInterface,
  deleteOntologyLinkInterface,
  deleteOntologyRelationCategoryTreeInterface,
  deleteOntologySpaceInterface,
  getExportOntologySpaceInterface,
  getOntologyCategoryTreeInterface,
  getOntologyOverviewCountInterface,
  getOntologyRelationCategoryTreeInterface,
  getOntologySpaceListInterface,
  getOntologySpaceStatisticInterface,
  postCreateOntologyCategoryTreeInterface,
  postCreateOntologyLinkInterface,
  postCreateOntologyRelationCategoryTreeInterface,
  postImportOntologySpaceInterface,
  postUploadOntologyThumbnailInterface,
  putUpdateOntologyCategoryNameInterface,
  putUpdateOntologyLinkInterface,
  putUpdateOntologyRelationCategoryNameInterface,
  updateOntologySpaceInterface,
} from "./ontologyManageApi";
import {
  createOntologyObjectArrTypeTreeInterface,
  deleteOntologyObjectArrTypeTreeInterface,
  getOntologyMetaByObjectIdInterface,
  getOntologyObjectArrTypeTreeInterface,
  updateOntologyObjectArrTypeTreeInterface,
} from "./ontologyObjectArrManageApi";
import {
  createOntologyObjectInterface,
  deleteOntologyObjectInterface,
  getExportOntologyInterface,
  getOntologyMetaStatisticInterface,
  getOntologyObjectByCategoryIdInterface,
  postImportOntologiesInterface,
  updateOntologyObjectInterface,
} from "./ontologyObjectManageApi";
import {
  autoBindOntologyPropertyDatasourceInterface,
  createOntologyPropertyInterface,
  deleteOntologyPropertyInterface,
  getOntologyPropertyByCategoryIdInterface,
  getOntologyPropertyByOntologyIdInterface,
  getOntologyPropertyDetailByOntologyIdInterface,
  putBatchUpdateOntologyPropertiesInterface,
  updateOntologyPropertyInterface,
} from "./ontologyPropertyApi";

export {
  autoBindOntologyPropertyDatasourceInterface,
  createOntologyFunctionInterface,
  createOntologySpaceInterface,
  createOntologySpaceWithCanvasContentInterface,
  createOntologyObjectInterface,
  createOntologyObjectArrTypeTreeInterface,
  createOntologyPropertyInterface,
  deleteOntologyObjectArrTypeTreeInterface,
  deleteOntologyCategoryTreeInterface,
  deleteOntologyLinkInterface,
  deleteOntologyObjectInterface,
  deleteOntologyRelationCategoryTreeInterface,
  deleteOntologySpaceInterface,
  deleteOntologyPropertyInterface,
  getExampleInterface,
  getExportOntologyInterface,
  getExportOntologySpaceInterface,
  getOntologyApiDocsInterface,
  getOntologyDatasourceColumnsInterface,
  getOntologyCategoryTreeInterface,
  getOntologyFunctionListInterface,
  getOntologyMetaByObjectIdInterface,
  getOntologyObjectArrTypeTreeInterface,
  getOntologyObjectByCategoryIdInterface,
  getOntologyPropertyByCategoryIdInterface,
  getOntologyPropertyByOntologyIdInterface,
  getOntologyPropertyDetailByOntologyIdInterface,
  getOntologyDatasourceTablesInterface,
  getOntologyMetaStatisticInterface,
  getOntologyOverviewCountInterface,
  getOntologyRelationCategoryTreeInterface,
  getOntologySpaceListInterface,
  getOntologySpaceStatisticInterface,
  postCreateOntologyCategoryTreeInterface,
  postCreateOntologyLinkInterface,
  postCreateOntologyRelationCategoryTreeInterface,
  postImportOntologiesInterface,
  postImportOntologySpaceInterface,
  postLoginInterface,
  postOntologyGlobalSearchInterface,
  postUploadOntologyThumbnailInterface,
  putBatchUpdateOntologyPropertiesInterface,
  putUpdateOntologyCategoryNameInterface,
  putUpdateOntologyLinkInterface,
  putUpdateOntologyRelationCategoryNameInterface,
  updateOntologySpaceInterface,
  updateOntologyObjectArrTypeTreeInterface,
  updateOntologyObjectInterface,
  updateOntologyPropertyInterface,
};
