import { getExampleInterface } from "./exampleApi";
import { postLoginInterface } from "./loginApi";
import {
  createOntologySpaceInterface,
  createOntologySpaceWithCanvasContentInterface,
  deleteOntologyCategoryTreeInterface,
  deleteOntologyLinkInterface,
  deleteOntologyRelationCategoryTreeInterface,
  deleteOntologySpaceInterface,
  getOntologyCategoryTreeInterface,
  getOntologyRelationCategoryTreeInterface,
  getOntologySpaceListInterface,
  postCreateOntologyCategoryTreeInterface,
  postCreateOntologyLinkInterface,
  postCreateOntologyRelationCategoryTreeInterface,
  putUpdateOntologyCategoryNameInterface,
  putUpdateOntologyRelationCategoryNameInterface,
  updateOntologySpaceInterface,
} from "./ontologyManageApi";
import {
  createOntologyObjectArrTypeTreeInterface,
  deleteOntologyObjectArrTypeTreeInterface,
  getOntologyObjectArrTypeTreeInterface,
  updateOntologyObjectArrTypeTreeInterface,
} from "./ontologyObjectArrManageApi";
import {
  createOntologyObjectInterface,
  deleteOntologyObjectInterface,
  getOntologyObjectByCategoryIdInterface,
  updateOntologyObjectInterface,
} from "./ontologyObjectManageApi";
import {
  autoBindOntologyPropertyDatasourceInterface,
  createOntologyPropertyInterface,
  deleteOntologyPropertyInterface,
  getOntologyPropertyByCategoryIdInterface,
  getOntologyPropertyByOntologyIdInterface,
  updateOntologyPropertyInterface,
} from "./ontologyPropertyApi";

export {
  autoBindOntologyPropertyDatasourceInterface,
  createOntologySpaceInterface,
  createOntologySpaceWithCanvasContentInterface,
  createOntologyObjectInterface,
  createOntologyObjectArrTypeTreeInterface,
  createOntologyPropertyInterface,
  deleteOntologyObjectArrTypeTreeInterface,
  deleteOntologyCategoryTreeInterface,
  deleteOntologyLinkInterface,
  deleteOntologyObjectInterface,
  deleteOntologyRelationCategoryTreeInterface,
  deleteOntologySpaceInterface,
  deleteOntologyPropertyInterface,
  getExampleInterface,
  getOntologyCategoryTreeInterface,
  getOntologyObjectArrTypeTreeInterface,
  getOntologyObjectByCategoryIdInterface,
  getOntologyPropertyByCategoryIdInterface,
  getOntologyPropertyByOntologyIdInterface,
  getOntologyRelationCategoryTreeInterface,
  getOntologySpaceListInterface,
  postCreateOntologyCategoryTreeInterface,
  postCreateOntologyLinkInterface,
  postCreateOntologyRelationCategoryTreeInterface,
  postLoginInterface,
  putUpdateOntologyCategoryNameInterface,
  putUpdateOntologyRelationCategoryNameInterface,
  updateOntologySpaceInterface,
  updateOntologyObjectArrTypeTreeInterface,
  updateOntologyObjectInterface,
  updateOntologyPropertyInterface,
};
